title: Trio Douze
email: akg@trio-douze.at
description: >-
  Die Musiker des "Trio Douze" sind allesamt Mitglieder des Vereines "KIBU". Um die regelmässigen
  KIBU-Konzerte abwechslungsreicher zu gestalten, entstand die Idee, ein Ensemble in nicht
  alltäglicher Besetzung ins Leben zu rufen.
baseurl: ""
url: ""
markdown: kramdown
theme: minima
header_pages:
  - biografie.md
  - cd.md
  - fotos.md
  - kritik.md
google_analytics: UA-109133087-1
defaults:
  - scope:
      path: "assets/photos"
    values:
      photo: true